import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { signIn } from "next-auth/react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { loginSchema, ILogin } from "../server/common/Validation/auth";

const Home: NextPage = () => {
  const router = useRouter();
  const [toast, setToast] = useState(false);
  const { register, handleSubmit } = useForm<ILogin>({
    resolver: zodResolver(loginSchema),
  });

  const onSubmit = async (data: ILogin) => {
    try {
      const result = await signIn("credentials", { ...data, redirect: false });
      console.log(result);
      if (!result.ok) {
        setToast(true);
      } else {
        router.push("/dashboard");
      }
    } catch (e) {
      console.log(e);
    }
  };

  return (
    <div>
      <Head>
        <title>Next App - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form
          className="flex h-screen w-full items-center justify-center"
          onSubmit={handleSubmit(onSubmit)}
        >
          {toast && (
            <div className="toast">
              <div className="alert alert-warning">
                <div>
                  <span>There is an error.</span>
                </div>
              </div>
            </div>
          )}

          <div className="card w-96 bg-base-100 shadow-xl">
            <div className="card-body">
              <h1>Welcome back!</h1>
              <input
                type="email"
                placeholder="Type your email..."
                className="input-bordered input mt-2 w-full max-w-xs"
                {...register("email")}
              />
              <input
                type="password"
                placeholder="Type your password..."
                className="input-bordered input my-2 w-full max-w-xs"
                {...register("password")}
              />
              <div className="card-actions items-center justify-between">
                <Link href="/sign-up" className="link">
                  Go to sign up
                </Link>
                <button className="btn-secondary btn" type="submit">
                  Login please
                </button>
              </div>
            </div>
          </div>
        </form>
      </main>
    </div>
  );
};

export default Home;
